import {useCallback,useEffect,useMemo,useState} from 'react'
import {Handle,Position,ReactFlow} from '@xyflow/react'
import '@xyflow/react/dist/style.css'
import {BrainCircuit,CheckCircle2,Database,Droplets,Eye,History,Info as InfoIcon,Leaf,LoaderCircle,TrendingUp,X} from 'lucide-react'
import {getAiRetrainingRequest,restoreAiModelRequest,trainAiRequest} from '@/auth/ai.service.js'
import {useToast} from '@/context/useToast.js'
import decisionTreeImage from '@/assets/ai-decision-tree-cartoon.png'

const date=value=>value?new Date(value).toLocaleString('es-GT',{dateStyle:'medium',timeStyle:'short'}):'Sin registro'
const pct=value=>`${Number(value||0).toFixed(1)} %`
const number=(value,suffix='')=>value===null||value===undefined||value===''?'--':`${Number(value).toFixed(1)}${suffix}`
const accuracy=value=>{const n=Number(value||0);return Math.max(0,Math.min(100,n<=1?n*100:n))}

function DecisionNode({data}){
 const irrigation=data.decision==='REGAR'
 return <div className={`w-40 transition ${data.selected?'scale-105':''}`}>
  <div style={{animationDelay:`${data.swayDelay}s`}} className={`ai-tree-decision-card ai-wood-plaque relative border-2 shadow-lg ${data.selected?'border-amber-300 ring-4 ring-amber-200/80':data.currentBase?'border-slate-100 ring-4 ring-slate-400/80':'border-[#643715]'} ${data.latest?'opacity-90':''}`}>
   <Handle type="target" position={Position.Bottom} className="!size-2.5 !border-amber-100 !bg-[#77451f]"/>
   <div className="flex items-center justify-between gap-2 border-b border-[#74431f] px-2.5 py-2">
    <span className="flex min-w-0 items-center gap-1.5 text-[10px] font-black uppercase text-white"><Leaf className={`size-4 shrink-0 fill-current ${irrigation?'text-sky-200':'text-lime-200'}`}/><span className="truncate">{data.currentBase?'Modelo actual':data.root?'Más antigua':data.latest?'Última decisión':`Decisión #${data.id}`}</span></span>
    <button type="button" title="Ver detalles" aria-label={`Ver detalles de la decisión ${data.id}`} onClick={event=>{event.stopPropagation();data.onDetails()}} className="grid size-6 shrink-0 place-items-center border border-amber-100/70 bg-white/15 text-white hover:bg-white/25"><Eye className="size-3.5"/></button>
   </div>
   <div className="px-2.5 py-2 text-amber-50"><div className="flex items-end justify-between gap-2"><strong className={`text-xs ${irrigation?'text-sky-100':'text-lime-100'}`}>{data.decision.replace('_',' ')}</strong><span className="text-xs font-black">{number(data.variables?.humedad,' %')}</span></div><p className="mt-1 text-[9px] font-semibold text-amber-100/90">{data.samples} lecturas conservadas</p></div>
   <Handle type="source" position={Position.Top} className="!size-2.5 !border-amber-100 !bg-[#77451f]"/>
  </div>
 </div>
}

const nodeTypes={decision:DecisionNode}
const TREE_POSITIONS=[{x:430,y:545},{x:235,y:420},{x:625,y:420},{x:55,y:285},{x:280,y:270},{x:525,y:260},{x:765,y:290},{x:145,y:105},{x:415,y:70},{x:700,y:115}]

export function AIRetrainingContent(){
 const toast=useToast(),[data,setData]=useState({}),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(''),[action,setAction]=useState(''),[elapsed,setElapsed]=useState(0),[selectedId,setSelectedId]=useState(null),[restore,setRestore]=useState(null),[reason,setReason]=useState(''),[trainConfirm,setTrainConfirm]=useState(false)
 const load=useCallback(async()=>{setLoading(true);setLoadError('');try{setData(await getAiRetrainingRequest())}catch(error){setLoadError(error.message);toast.error(error.message)}finally{setLoading(false)}},[toast])
 useEffect(()=>{load();const refresh=()=>load();window.addEventListener('focus',refresh);window.addEventListener('project:changed',refresh);return()=>{window.removeEventListener('focus',refresh);window.removeEventListener('project:changed',refresh)}},[load])
 useEffect(()=>{if(action!=='train'){setElapsed(0);return undefined}const started=Date.now(),timer=window.setInterval(()=>setElapsed(Math.floor((Date.now()-started)/1000)),1000);return()=>window.clearInterval(timer)},[action])
 const tree=useMemo(()=>Array.isArray(data.arbol)?data.arbol.slice(-10):[],[data.arbol])
 const selected=tree.find(item=>Number(item.id)===Number(selectedId))||null
 const excludedDecisions=selected?tree.filter(item=>new Date(item.fecha_hora)>new Date(selected.fecha_hora)).length:0
 const trainingTotal=selected?Number(selected.muestras_historicas||0)+Number(selected.muestras_referencia||0)+(Number(selected.correcciones_humanas||0)*5):0
 const nodes=useMemo(()=>tree.map((item,index)=>({id:String(item.id),type:'decision',position:TREE_POSITIONS[index],zIndex:5,data:{id:item.id,decision:item.decision,variables:item.variables_entrada,samples:item.muestras_historicas||0,selected:Number(item.id)===Number(selectedId),currentBase:Boolean(item.es_base_modelo),root:index===0,latest:Boolean(item.es_ultima)||index===tree.length-1,swayDelay:(index%5)*-.45,onDetails:()=>setSelectedId(Number(item.id))}})),[tree,selectedId])
 const edges=useMemo(()=>tree.slice(1).map((item,index)=>{const child=index+1,parent=Math.floor((child-1)/2);return{id:`e-${tree[parent].id}-${item.id}`,source:String(tree[parent].id),target:String(item.id),animated:true,type:'bezier',style:{stroke:'#865027',strokeWidth:3}}}),[tree])
 const train=async()=>{if(!selected||selected.es_ultima)return;setTrainConfirm(false);setAction('train');try{const response=await trainAiRequest({decisionId:selected.id});toast.success(response?.message||'Modelo entrenado.');setSelectedId(null);await load()}catch(error){toast.error(error.message)}finally{setAction('')}}
 const confirmRestore=async()=>{setAction('restore');try{const response=await restoreAiModelRequest(restore.id,{motivo:reason});toast.success(response?.message||'Versión restaurada.');setRestore(null);setReason('');await load()}catch(error){toast.error(error.message)}finally{setAction('')}}
 const summary=data.resumen||{},versions=Array.isArray(data.versiones)?data.versiones:[]

 return <div className="mx-auto max-w-[1500px] space-y-5">
  <header className="border-b border-slate-200 pb-5"><p className="text-xs font-semibold uppercase text-emerald-700">Inteligencia artificial</p><h1 className="mt-1 text-3xl font-bold text-slate-950">Árbol histórico de decisiones</h1><p className="mt-1 max-w-3xl text-sm text-slate-600">Explora el aprendizaje del modelo y elige un punto anterior para generar una versión nueva sin utilizar la información posterior.</p></header>
  <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['Decisiones históricas',summary.total||0,History],['Recomendó regar',pct(summary.porcentajeRegar),TrendingUp],['Recomendó no regar',pct(summary.porcentajeNoRegar),Droplets],['Acuerdo humano',pct(summary.porcentajeAcuerdo),CheckCircle2]].map(([label,value,Icon])=><div key={label} className="border border-slate-200 bg-white p-4"><div className="flex items-center justify-between text-sm text-slate-500"><span>{label}</span><Icon className="size-4"/></div><p className="mt-2 text-2xl font-bold text-slate-950">{value}</p></div>)}</section>

  <section className="overflow-hidden border border-slate-300 bg-white"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 px-5 py-4"><div><h2 className="font-bold text-slate-950">Recorrido del modelo</h2><p className="text-sm text-slate-500">Hasta diez decisiones: la más antigua visible nace cerca de la raíz y la más reciente llega a la copa.</p></div><div className="flex gap-3 text-xs font-semibold"><span className="flex items-center gap-1.5"><i className="size-3 bg-sky-600"/>REGAR</span><span className="flex items-center gap-1.5"><i className="size-3 bg-emerald-600"/>NO REGAR</span></div></div>
   <div className="grid min-h-[700px] xl:grid-cols-[minmax(0,1fr)_340px]">
    <div className="relative h-[700px] min-w-0 overflow-hidden bg-slate-50"><img src={decisionTreeImage} alt="" aria-hidden="true" className="ai-decision-tree-image pointer-events-none absolute inset-0 z-0 size-full object-contain object-bottom opacity-90"/>{loading?<TreeMessage title="Cargando decisiones" detail="Consultando el recorrido del proyecto activo." loading/>:loadError?<TreeMessage title="No se pudo cargar el recorrido" detail={loadError} action={load}/>:tree.length===0?<TreeMessage title="Todavía no hay decisiones" detail="Evalúa la IA al menos una vez para crear el primer punto del recorrido."/>:<ReactFlow key={tree.map(item=>item.id).join('-')} className="ai-tree-flow !absolute !inset-0 !z-10" nodes={nodes} edges={edges} nodeTypes={nodeTypes} onNodeClick={(_,node)=>setSelectedId(Number(node.id))} fitView fitViewOptions={{padding:.06,maxZoom:1}} nodesDraggable={false} nodesConnectable={false} panOnDrag={false} zoomOnScroll={false} zoomOnPinch={false} zoomOnDoubleClick={false} preventScrolling={false} proOptions={{hideAttribution:true}}/>}</div>
    <aside className="border-t border-slate-200 bg-white p-5 xl:border-l xl:border-t-0">{selected?<DecisionDetails selected={selected} excludedDecisions={excludedDecisions} trainingTotal={trainingTotal} onTrain={()=>setTrainConfirm(true)}/>:<div className="flex h-full min-h-56 flex-col justify-center"><div className="grid size-11 place-items-center bg-emerald-50 text-emerald-700"><InfoIcon className="size-5"/></div><h3 className="mt-4 font-bold text-slate-900">Cómo leer el recorrido</h3><p className="mt-2 text-sm leading-6 text-slate-600">Cada tablón representa una recomendación. Abre sus detalles para conocer los datos disponibles en ese momento y el efecto de regresar a ese punto.</p><div className="mt-5 border-l-4 border-slate-300 pl-3 text-sm text-slate-600">La última decisión solo puede consultarse: ya utiliza el conjunto actual y no representa un retroceso.</div></div>}</aside>
   </div>
  </section>

  <section className="border border-slate-200 bg-white"><div className="border-b border-slate-200 p-5"><h2 className="text-lg font-bold text-slate-950">Evolución y versiones del modelo</h2><p className="text-sm text-slate-500">La versión actual aparece en gris. Seleccionar una histórica la resalta antes de confirmar el cambio.</p></div><div className="divide-y divide-slate-200">{versions.map((item,index)=>{const score=accuracy(item.exactitud),previous=versions[index+1],delta=previous?score-accuracy(previous.exactitud):null,isSelected=Number(restore?.id)===Number(item.id);return <div key={item.id} className={`grid gap-3 border-l-4 p-4 text-sm md:grid-cols-[minmax(170px,1fr)_minmax(220px,1.4fr)_150px_auto] md:items-center ${item.sn_activo?'border-slate-500 bg-slate-100':isSelected?'border-amber-500 bg-amber-50':'border-transparent bg-white'}`}><div><div className="flex flex-wrap items-center gap-2"><strong>{item.version||`Modelo #${item.id}`}</strong>{item.sn_activo?<span className="bg-slate-700 px-2 py-0.5 text-[10px] font-bold text-white">ACTUAL</span>:isSelected?<span className="bg-amber-500 px-2 py-0.5 text-[10px] font-bold text-white">SELECCIONADA</span>:<span className="bg-white px-2 py-0.5 text-[10px] font-bold text-slate-500">HISTÓRICA</span>}</div><span className="mt-1 block text-xs text-slate-500">{item.total_muestras} muestras · {date(item.fecha_entrenamiento)}</span></div><div><div className="mb-1 flex justify-between text-xs"><span>Exactitud</span><strong>{score.toFixed(1)} % {delta!==null&&<span className={delta>=0?'text-emerald-700':'text-red-700'}>({delta>=0?'+':''}{delta.toFixed(1)})</span>}</strong></div><div className="h-2 bg-white"><div className="h-full bg-emerald-600 transition-all" style={{width:`${score}%`}}/></div></div><span className={item.sn_activo?'font-bold text-slate-700':'text-slate-500'}>{item.sn_activo?'Modelo utilizado para decidir':item.estado}</span>{item.sn_activo?<span className="text-xs font-semibold text-slate-600">En uso</span>:<button onClick={()=>{setRestore(item);setReason('')}} className={`h-9 border px-3 text-xs font-semibold ${isSelected?'border-amber-600 bg-amber-600 text-white':'border-slate-300 bg-white'}`}>{isSelected?'Modelo seleccionado':'Seleccionar versión'}</button>}</div>})}</div></section>

  {trainConfirm&&selected&&!selected.es_ultima&&<Modal title="Entrenar desde este punto" eyebrow={`Decisión #${selected.id}`} onClose={()=>setTrainConfirm(false)}><div className="space-y-4"><p className="text-sm leading-6 text-slate-600">Se creará un Random Forest nuevo con la información que existía hasta el {date(selected.fecha_hora)}. El modelo volverá a estudiar esos datos; no se restaura un archivo anterior.</p><div className="grid grid-cols-2 gap-2"><Info label="Lecturas históricas" value={selected.muestras_historicas||0}/><Info label="Correcciones humanas" value={selected.correcciones_humanas||0}/><Info label="Referencias sintéticas" value={selected.muestras_referencia||51}/><Info label="Filas estimadas" value={trainingTotal}/></div><div className="border-l-4 border-amber-500 bg-amber-50 p-3 text-sm text-amber-950">Se ignorarán {selected.muestras_posteriores||0} lecturas y {excludedDecisions} decisiones posteriores para este entrenamiento. No se borrarán del historial.</div><div className="grid grid-cols-2 gap-2"><button onClick={()=>setTrainConfirm(false)} className="h-11 border border-slate-300 font-semibold">Cancelar</button><button onClick={train} disabled={action==='train'} className="h-11 bg-slate-950 font-semibold text-white disabled:opacity-50">{action==='train'?'Entrenando...':'Crear nueva versión'}</button></div></div></Modal>}
  {restore&&<Modal title={`Restaurar ${restore.version}`} eyebrow="Cambio de versión" onClose={()=>setRestore(null)}><div className="space-y-4"><div className="border-l-4 border-amber-500 bg-amber-50 p-3 text-sm text-amber-950">Las recomendaciones pendientes serán canceladas y la versión quedará en modo supervisado.</div><label className="block text-sm font-semibold">Motivo obligatorio<textarea rows="4" value={reason} onChange={event=>setReason(event.target.value)} placeholder="Explica por qué necesitas volver a esta versión" className="mt-1 w-full resize-none border border-slate-300 p-3 font-normal"/></label><div className="grid grid-cols-2 gap-2"><button onClick={()=>setRestore(null)} className="h-11 border border-slate-300 font-semibold">Cancelar</button><button onClick={confirmRestore} disabled={action==='restore'||reason.trim().length<10} className="h-11 bg-red-700 font-semibold text-white disabled:opacity-50">{action==='restore'?'Restaurando...':'Confirmar restauración'}</button></div></div></Modal>}
  {action==='train'&&<TrainingScreen elapsed={elapsed}/>} 
 </div>
}

function TreeMessage({title,detail,loading=false,action}){return <div className="absolute inset-0 z-20 flex items-center justify-center bg-slate-50/80 p-6 text-center"><div className="max-w-sm bg-white p-6 shadow-lg">{loading?<LoaderCircle className="mx-auto size-8 animate-spin text-emerald-700"/>:<InfoIcon className="mx-auto size-8 text-emerald-700"/>}<h3 className="mt-3 font-bold text-slate-950">{title}</h3><p className="mt-1 text-sm text-slate-600">{detail}</p>{action&&<button onClick={action} className="mt-4 h-10 bg-slate-950 px-4 text-sm font-semibold text-white">Intentar nuevamente</button>}</div></div>}

function TrainingScreen({elapsed}){const stage=elapsed<2?'Preparando el corte histórico':elapsed<6?'Entrenando los árboles de decisión':'Guardando y validando la nueva versión';return <div className="fixed inset-0 z-[120] flex items-center justify-center bg-slate-950/75 p-4"><div role="status" aria-live="polite" className="w-full max-w-md bg-white p-7 text-center shadow-2xl"><div className="relative mx-auto grid size-20 place-items-center"><span className="absolute inset-0 animate-ping rounded-full bg-emerald-200 opacity-50"/><span className="relative grid size-16 place-items-center rounded-full bg-emerald-700 text-white"><BrainCircuit className="size-8"/></span></div><p className="mt-5 text-xs font-bold uppercase text-emerald-700">Reentrenamiento en proceso</p><h2 className="mt-2 text-xl font-bold text-slate-950">{stage}</h2><p className="mt-2 text-sm leading-6 text-slate-600">La IA está construyendo una versión nueva con el punto seleccionado. Mantén esta ventana abierta hasta recibir el resultado.</p><div className="ai-training-progress mt-6 h-2 overflow-hidden bg-slate-100"><span/></div><p className="mt-3 text-xs font-semibold text-slate-500">Tiempo transcurrido: {elapsed} s</p></div></div>}

function DecisionDetails({selected,excludedDecisions,trainingTotal,onTrain}){
 const latest=Boolean(selected.es_ultima)
 return <div className="space-y-5"><div><div className="flex items-center justify-between gap-2"><div><p className="text-xs font-bold uppercase text-emerald-700">Detalle del punto</p><h3 className="mt-1 text-xl font-black">Decisión #{selected.id}</h3></div>{latest&&<span className="bg-slate-100 px-2 py-1 text-[10px] font-bold uppercase text-slate-600">Actual</span>}</div><p className="mt-1 text-xs text-slate-500">{date(selected.fecha_hora)}</p></div><div className="grid grid-cols-2 gap-2"><Info label="Recomendación" value={selected.decision?.replace('_',' ')}/><Info label="Estado" value={selected.estado}/><Info label="Humedad" value={number(selected.variables_entrada?.humedad,' %')}/><Info label="Temperatura" value={number(selected.variables_entrada?.temperatura,' °C')}/></div><div><h4 className="flex items-center gap-2 text-sm font-bold text-slate-900"><Database className="size-4"/>Datos del nuevo entrenamiento</h4><div className="mt-2 grid grid-cols-2 gap-2"><Info label="Lecturas conservadas" value={selected.muestras_historicas||0}/><Info label="Correcciones" value={selected.correcciones_humanas||0}/><Info label="Referencias" value={selected.muestras_referencia||51}/><Info label="Filas estimadas" value={trainingTotal}/></div></div>{latest?<div className="border-l-4 border-slate-400 bg-slate-50 p-3 text-sm text-slate-700"><strong>Decisión actual.</strong><p className="mt-1">No se puede reentrenar desde aquí porque no existen datos posteriores que retirar. Usa una decisión anterior para evaluar otro corte.</p></div>:<><div className="border-l-4 border-amber-500 bg-amber-50 p-3 text-sm text-amber-950"><strong>Punto de corte.</strong><p className="mt-1">El nuevo modelo ignorará {selected.muestras_posteriores||0} lecturas y {excludedDecisions} decisiones posteriores, sin eliminarlas de la auditoría.</p></div><button onClick={onTrain} className="inline-flex h-11 w-full items-center justify-center gap-2 bg-slate-950 text-sm font-semibold text-white"><BrainCircuit className="size-4"/>Entrenar desde aquí</button></>}</div>
}

function Info({label,value}){return <div className="bg-slate-50 p-2.5"><p className="text-[10px] font-bold uppercase text-slate-400">{label}</p><p className="mt-1 break-words text-sm font-bold text-slate-900">{value??'--'}</p></div>}
function Modal({title,eyebrow,onClose,children}){return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/55 p-4"><div role="dialog" aria-modal="true" className="w-full max-w-lg bg-white shadow-2xl"><div className="flex items-start justify-between border-b border-slate-200 p-5"><div><p className="text-xs font-semibold uppercase text-amber-700">{eyebrow}</p><h2 className="mt-1 text-xl font-bold">{title}</h2></div><button title="Cerrar" onClick={onClose}><X className="size-5"/></button></div><div className="p-5">{children}</div></div></div>}
