import {useCallback,useEffect,useState} from 'react'
import {CalendarDays,ChevronLeft,ChevronRight,ClipboardList,Download,Filter,RefreshCcw,Search,UserRound,UsersRound,X} from 'lucide-react'
import {useLocation} from 'react-router-dom'
import {searchAuditRequest} from '@/auth/audit.service.js'
import {useToast} from '@/context/useToast.js'

const initial={buscar:'',categoria:'',usuario:'',accion:'',desde:'',hasta:'',pagina:1,tamano:10}
const date=value=>value?new Date(value).toLocaleString('es-GT',{dateStyle:'medium',timeStyle:'short'}):'Sin registro'
const csvCell=value=>`"${String(value??'').replaceAll('"','""')}"`

export function AuditContent(){
 const history=useLocation().pathname.endsWith('/historial'),toast=useToast(),[filters,setFilters]=useState(initial),[query,setQuery]=useState(initial),[data,setData]=useState({}),[loading,setLoading]=useState(true),[selected,setSelected]=useState(null)
 const load=useCallback(async()=>{setLoading(true);try{setData(await searchAuditRequest(query))}catch(error){toast.error(error.message)}finally{setLoading(false)}},[query,toast])
 useEffect(()=>{load()},[load])
 const apply=event=>{event?.preventDefault();setQuery({...filters,pagina:1})}
 const reset=()=>{setFilters(initial);setQuery(initial)}
 const changePage=page=>{setFilters(current=>({...current,pagina:page}));setQuery(current=>({...current,pagina:page}))}
 const exportCsv=()=>{const rows=data.registros||[];if(!rows.length){toast.warning('No hay registros visibles para exportar.');return}const header=['Fecha','Usuario','Acción','Categoría','Entidad','Detalle','Valor anterior','Valor nuevo'];const body=rows.map(row=>[date(row.fecha_hora),row.usuario,row.accion_realizada,row.categoria,row.entidad?`${row.entidad} #${row.entidad_id||''}`:'',row.detalle,JSON.stringify(row.valores_anteriores||''),JSON.stringify(row.valores_nuevos||'')].map(csvCell).join(','));const blob=new Blob([`\uFEFF${header.map(csvCell).join(',')}\n${body.join('\n')}`],{type:'text/csv;charset=utf-8'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`auditoria-pagina-${data.paginacion?.pagina||1}.csv`;link.click();URL.revokeObjectURL(link.href)}
 const rows=Array.isArray(data.registros)?data.registros:[],summary=data.resumen||{},options=data.filtros||{},paging=data.paginacion||{pagina:1,paginas:1,total:0}
 return <div className="mx-auto max-w-7xl space-y-5">
  <header className="flex flex-col gap-4 border-b border-slate-200 pb-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase text-emerald-700">Auditoría de acciones</p><h1 className="mt-1 text-3xl font-bold text-slate-950">{history?'Histórico de acciones':'Búsqueda de auditoría'}</h1><p className="mt-1 text-sm text-slate-600">{history?'Secuencia cronológica de operaciones realizadas por usuarios del proyecto.':'Localiza cambios por responsable, categoría, acción o periodo.'}</p></div><div className="flex gap-2"><button title="Actualizar" onClick={load} disabled={loading} className="grid size-11 place-items-center border border-slate-300 bg-white"><RefreshCcw className={`size-4 ${loading?'animate-spin':''}`}/></button><button onClick={exportCsv} className="inline-flex h-11 items-center gap-2 border border-slate-300 bg-white px-4 text-sm font-semibold"><Download className="size-4"/>Exportar página</button></div></header>
  <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['Acciones registradas',summary.total||0,ClipboardList],['Realizadas hoy',summary.hoy||0,CalendarDays],['Usuarios responsables',summary.usuarios||0,UsersRound],['Categorías utilizadas',summary.categorias||0,Filter]].map(([label,value,Icon])=><div key={label} className="border border-slate-200 bg-white p-4"><div className="flex items-center justify-between text-sm text-slate-500"><span>{label}</span><Icon className="size-4"/></div><p className="mt-2 text-2xl font-bold text-slate-950">{value}</p></div>)}</section>
  {!history&&<form onSubmit={apply} className="border border-slate-200 bg-white p-5"><div className="mb-4 flex items-center gap-2"><Search className="size-5 text-emerald-700"/><h2 className="font-bold text-slate-950">Criterios de búsqueda</h2></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Field label="Texto"><input value={filters.buscar} onChange={e=>setFilters(f=>({...f,buscar:e.target.value}))} placeholder="Acción, detalle o entidad" className="h-11 w-full border border-slate-300 px-3"/></Field><Field label="Usuario"><select value={filters.usuario} onChange={e=>setFilters(f=>({...f,usuario:e.target.value}))} className="h-11 w-full border border-slate-300 bg-white px-3"><option value="">Todos</option>{(options.usuarios||[]).map(item=><option key={item.id} value={item.id}>{item.nombre}</option>)}</select></Field><Field label="Categoría"><select value={filters.categoria} onChange={e=>setFilters(f=>({...f,categoria:e.target.value}))} className="h-11 w-full border border-slate-300 bg-white px-3"><option value="">Todas</option>{(options.categorias||[]).map(item=><option key={item}>{item}</option>)}</select></Field><Field label="Acción"><select value={filters.accion} onChange={e=>setFilters(f=>({...f,accion:e.target.value}))} className="h-11 w-full border border-slate-300 bg-white px-3"><option value="">Todas</option>{(options.acciones||[]).map(item=><option key={item}>{item}</option>)}</select></Field><Field label="Desde"><input type="date" value={filters.desde} onChange={e=>setFilters(f=>({...f,desde:e.target.value}))} className="h-11 w-full border border-slate-300 px-3"/></Field><Field label="Hasta"><input type="date" value={filters.hasta} onChange={e=>setFilters(f=>({...f,hasta:e.target.value}))} className="h-11 w-full border border-slate-300 px-3"/></Field><Field label="Filas por página"><select value={filters.tamano} onChange={e=>setFilters(f=>({...f,tamano:e.target.value}))} className="h-11 w-full border border-slate-300 bg-white px-3"><option value="5">5</option><option value="10">10</option><option value="25">25</option><option value="50">50</option></select></Field><div className="flex items-end gap-2"><button type="button" onClick={reset} className="h-11 flex-1 border border-slate-300 font-semibold">Limpiar</button><button className="h-11 flex-1 bg-emerald-700 font-semibold text-white">Buscar</button></div></div></form>}
  <section className="border border-slate-200 bg-white"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 p-5"><div><h2 className="font-bold text-slate-950">{history?'Línea temporal de usuarios':'Resultados'}</h2><p className="text-sm text-slate-500">{paging.total||0} acción(es) encontradas. Se excluyen procesos automáticos y decisiones generadas por IA.</p></div>{history&&<label className="text-sm font-semibold">Filas <select value={query.tamano} onChange={e=>{const tamano=e.target.value;setFilters(f=>({...f,tamano,pagina:1}));setQuery(q=>({...q,tamano,pagina:1}))}} className="ml-2 h-9 border border-slate-300 bg-white px-2"><option value="5">5</option><option value="10">10</option><option value="25">25</option></select></label>}</div>{loading?<p className="p-10 text-center text-sm text-slate-500">Consultando auditoría...</p>:rows.length?<div className="divide-y divide-slate-100">{rows.map(row=><button key={row.id} onClick={()=>setSelected(row)} className="flex w-full items-start gap-4 p-5 text-left hover:bg-slate-50"><span className="grid size-10 shrink-0 place-items-center bg-slate-100 text-slate-700"><UserRound className="size-5"/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-bold text-slate-950">{row.accion_realizada}</p><span className="bg-emerald-50 px-2 py-0.5 text-xs font-bold text-emerald-800">{row.categoria}</span></div><p className="mt-1 text-sm text-slate-600">{row.detalle||'Sin detalle adicional.'}</p><p className="mt-1 text-xs text-slate-400">{row.usuario} · {date(row.fecha_hora)}</p></div><ChevronRight className="mt-2 size-4 shrink-0 text-slate-400"/></button>)}</div>:<p className="p-10 text-center text-sm text-slate-500">No hay acciones de usuarios que coincidan con los filtros.</p>}<div className="flex items-center justify-between border-t border-slate-200 px-5 py-3 text-sm"><span>Página {paging.pagina||1} de {paging.paginas||1}</span><div className="flex gap-2"><button title="Página anterior" disabled={(paging.pagina||1)<=1} onClick={()=>changePage(paging.pagina-1)} className="grid size-9 place-items-center border border-slate-300 disabled:opacity-40"><ChevronLeft className="size-4"/></button><button title="Página siguiente" disabled={(paging.pagina||1)>=(paging.paginas||1)} onClick={()=>changePage(paging.pagina+1)} className="grid size-9 place-items-center border border-slate-300 disabled:opacity-40"><ChevronRight className="size-4"/></button></div></div></section>
  {selected&&<AuditModal row={selected} onClose={()=>setSelected(null)}/>} 
 </div>
}

function Field({label,children}){return <label className="block text-sm font-semibold text-slate-700"><span className="mb-1 block">{label}</span>{children}</label>}
function JsonBlock({label,value}){return <div><p className="mb-1 text-xs font-bold uppercase text-slate-500">{label}</p><pre className="max-h-48 overflow-auto whitespace-pre-wrap border border-slate-200 bg-slate-50 p-3 text-xs text-slate-700">{value?JSON.stringify(value,null,2):'Sin datos'}</pre></div>}
function AuditModal({row,onClose}){return <div className="fixed inset-0 z-[90] flex items-center justify-center bg-slate-950/55 p-4"><div role="dialog" aria-modal="true" className="max-h-[90vh] w-full max-w-2xl overflow-y-auto bg-white shadow-2xl"><div className="flex items-start justify-between border-b border-slate-200 p-5"><div><p className="text-xs font-semibold uppercase text-emerald-700">Registro #{row.id}</p><h2 className="mt-1 text-xl font-bold text-slate-950">{row.accion_realizada}</h2></div><button title="Cerrar" onClick={onClose} className="grid size-9 place-items-center border border-slate-300"><X className="size-4"/></button></div><div className="space-y-5 p-5"><div className="grid gap-3 sm:grid-cols-2"><Info label="Responsable" value={row.usuario}/><Info label="Fecha" value={date(row.fecha_hora)}/><Info label="Categoría" value={row.categoria}/><Info label="Entidad" value={row.entidad?`${row.entidad}${row.entidad_id?` #${row.entidad_id}`:''}`:'Sin entidad'}/></div><div><p className="mb-1 text-xs font-bold uppercase text-slate-500">Detalle</p><p className="border-l-4 border-emerald-600 bg-emerald-50 p-3 text-sm text-slate-700">{row.detalle||'Sin detalle adicional.'}</p></div><div className="grid gap-4 md:grid-cols-2"><JsonBlock label="Valores anteriores" value={row.valores_anteriores}/><JsonBlock label="Valores nuevos" value={row.valores_nuevos}/></div></div></div></div>}
function Info({label,value}){return <div className="bg-slate-50 p-3"><p className="text-xs font-bold uppercase text-slate-500">{label}</p><p className="mt-1 break-words text-sm font-semibold text-slate-900">{value}</p></div>}
