import { useCallback,useEffect,useMemo,useState } from 'react'
import { ExternalLink,Paperclip,Search } from 'lucide-react'
import { listFieldReportsRequest,openReportAttachmentRequest } from '@/auth/reports.service.js'
import { useToast } from '@/context/useToast.js'

const formatDate=value=>value?new Date(value).toLocaleDateString('es-GT'):'—'

export function FieldReportListContent(){
 const toast=useToast();const[rows,setRows]=useState([]);const[query,setQuery]=useState('');const[selected,setSelected]=useState(null)
 const load=useCallback(()=>listFieldReportsRequest().then(setRows).catch(error=>toast.error(error.message)),[toast])
 useEffect(()=>{load()},[load])
 const filtered=useMemo(()=>{const term=query.trim().toLowerCase();return term?rows.filter(row=>[row.titulo,row.asunto,row.usuario,row.estado_general].some(value=>String(value||'').toLowerCase().includes(term))):rows},[query,rows])
 const open=async file=>{try{await openReportAttachmentRequest(file)}catch(error){toast.error(error.message)}}
 return <div className="space-y-4"><div className="relative"><Search className="absolute left-3 top-3 text-slate-400" size={18}/><input value={query} onChange={event=>setQuery(event.target.value)} className="w-full rounded-xl border border-slate-200 bg-white py-3 pl-10 pr-4 outline-none focus:border-green-600" placeholder="Buscar por título, asunto, responsable o estado"/></div><div className="overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="grid grid-cols-[90px_1fr_150px_120px] gap-3 border-b bg-slate-50 px-4 py-3 text-xs font-black uppercase text-slate-500"><span>Número</span><span>Informe</span><span>Fecha</span><span>Estado</span></div>{filtered.length?filtered.map(row=><button key={row.id} onClick={()=>setSelected(row)} className="grid w-full grid-cols-[90px_1fr_150px_120px] gap-3 border-b px-4 py-3 text-left text-sm hover:bg-slate-50"><strong className="text-green-800">#{String(row.id).padStart(4,'0')}</strong><span className="min-w-0"><strong className="block truncate">{row.titulo}</strong><small className="text-slate-500">{row.usuario||'Sistema'} · {row.adjuntos?.length||0} adjuntos</small></span><span>{formatDate(row.fecha_observacion)}</span><span>{row.estado_general||'Sin estado'}</span></button>):<p className="p-8 text-center text-sm text-slate-500">No se encontraron informes.</p>}</div>{selected?<div className="fixed inset-0 z-[90] flex items-center justify-center bg-black/50 p-4" onMouseDown={()=>setSelected(null)}><div className="max-h-[90vh] w-full max-w-2xl overflow-auto rounded-2xl bg-white p-6" onMouseDown={event=>event.stopPropagation()}><div className="flex justify-between gap-4"><div><p className="text-xs font-black text-green-700">INFORME #{String(selected.id).padStart(4,'0')}</p><h2 className="text-2xl font-black">{selected.titulo}</h2></div><button onClick={()=>setSelected(null)}>Cerrar</button></div><p className="mt-5 whitespace-pre-wrap text-sm text-slate-700">{selected.observaciones}</p><h3 className="mt-6 text-sm font-black">Archivos adjuntos</h3><div className="mt-2 space-y-2">{selected.adjuntos?.length?selected.adjuntos.map(file=><button key={file.id} onClick={()=>open(file)} className="flex w-full items-center gap-3 rounded-lg border p-3 text-left"><Paperclip size={16}/><span className="flex-1 truncate">{file.nombre}</span><ExternalLink size={15}/></button>):<p className="text-sm text-slate-500">Sin archivos adjuntos.</p>}</div></div></div>:null}</div>
}
