import {useEffect,useState} from 'react'
import {AlertTriangle,LockKeyhole,PencilLine,X} from 'lucide-react'
import {correctInitialParametersRequest,getActiveProject,getCropParametersRequest,listCropsRequest} from '@/auth/projects.service.js'
import {useToast} from '@/context/useToast.js'

const empty={cultivoId:'',variedad:'',fechaSiembra:'',tiempoCosechaDias:'',humedadMinima:'',humedadMaxima:'',temperaturaMinima:'',temperaturaMaxima:'',observaciones:''}
export function InitialParametersContent(){
 const project=getActiveProject(),canManage=Number(project?.rol_id)===1,toast=useToast(),[form,setForm]=useState(empty),[crops,setCrops]=useState([]),[loading,setLoading]=useState(true),[editing,setEditing]=useState(false),[confirm,setConfirm]=useState(false),[reason,setReason]=useState(''),[saving,setSaving]=useState(false)
 useEffect(()=>{Promise.all([getCropParametersRequest(project.id),listCropsRequest()]).then(([data,list])=>{setCrops(list);setForm({cultivoId:data?.cultivo_id||'',variedad:data?.variedad||'',fechaSiembra:data?.fecha_siembra?.slice(0,10)||'',tiempoCosechaDias:data?.tiempo_cosecha_dias??'',humedadMinima:data?.humedad_minima??'',humedadMaxima:data?.humedad_maxima??'',temperaturaMinima:data?.temperatura_minima??'',temperaturaMaxima:data?.temperatura_maxima??'',observaciones:data?.observaciones||''})}).catch(e=>toast.error(e.message)).finally(()=>setLoading(false))},[project.id,toast])
 const change=(key,value)=>setForm(current=>({...current,[key]:value}))
 const submit=async()=>{setSaving(true);try{const message=await correctInitialParametersRequest(project.id,{...form,motivo:reason});toast.success(message);setConfirm(false);setEditing(false);setReason('')}catch(e){toast.error(e.message)}finally{setSaving(false)}}
 if(loading)return <div className="border border-slate-200 bg-white p-8 text-slate-500">Consultando parámetros iniciales...</div>
 return <section className="mx-auto max-w-6xl space-y-5">
  <header><p className="text-xs font-semibold uppercase text-emerald-700">Datos maestros</p><h1 className="mt-1 text-3xl font-bold text-slate-950">Parámetros iniciales</h1><p className="mt-1 text-sm text-slate-600">Corrección excepcional de los valores usados por alertas, riego e inteligencia artificial.</p></header>
  <div className="flex items-start gap-3 border-l-4 border-amber-500 bg-amber-50 p-4"><AlertTriangle className="mt-0.5 size-5 shrink-0 text-amber-700"/><div className="text-sm text-amber-950"><strong>Configuración protegida.</strong><p className="mt-1">Modifícala únicamente para corregir un dato equivocado. Al guardar, la IA volverá a revisión y el modo automático se desactivará.</p></div></div>
   <div className="border border-slate-200 bg-white"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 p-5"><div><h2 className="font-bold text-slate-950">Valores del proyecto</h2><p className="text-sm text-slate-500">Proyecto: {project.nombre}</p></div>{canManage?(!editing?<button onClick={()=>setEditing(true)} className="inline-flex h-10 items-center gap-2 border border-amber-600 px-4 text-sm font-semibold text-amber-800"><PencilLine className="size-4"/>Habilitar corrección</button>:<span className="inline-flex items-center gap-2 bg-amber-100 px-3 py-2 text-sm font-semibold text-amber-900"><LockKeyhole className="size-4"/>Edición habilitada</span>):<span className="text-sm text-slate-500">Solo lectura</span>}</div>
   <div className="grid gap-4 p-5 md:grid-cols-2 lg:grid-cols-3">
    <Field label="Cultivo"><select disabled={!editing} value={form.cultivoId} onChange={e=>change('cultivoId',e.target.value)} className="input"><option value="">Selecciona un cultivo</option>{crops.map(c=><option key={c.id} value={c.id}>{c.nombre}</option>)}</select></Field>
    <Field label="Variedad"><input disabled={!editing} value={form.variedad} onChange={e=>change('variedad',e.target.value)} className="input"/></Field>
    <Field label="Fecha de siembra"><input type="date" disabled={!editing} value={form.fechaSiembra} onChange={e=>change('fechaSiembra',e.target.value)} className="input"/></Field>
    <Field label="Cosecha estimada (días)"><input type="number" min="1" max="3650" disabled={!editing} value={form.tiempoCosechaDias} onChange={e=>change('tiempoCosechaDias',e.target.value)} className="input"/></Field>
    <Field label="Humedad mínima (%)"><input type="number" min="0" max="100" step="0.1" disabled={!editing} value={form.humedadMinima} onChange={e=>change('humedadMinima',e.target.value)} className="input"/></Field>
    <Field label="Humedad máxima (%)"><input type="number" min="0" max="100" step="0.1" disabled={!editing} value={form.humedadMaxima} onChange={e=>change('humedadMaxima',e.target.value)} className="input"/></Field>
    <Field label="Temperatura mínima (°C)"><input type="number" step="0.1" disabled={!editing} value={form.temperaturaMinima} onChange={e=>change('temperaturaMinima',e.target.value)} className="input"/></Field>
    <Field label="Temperatura máxima (°C)"><input type="number" step="0.1" disabled={!editing} value={form.temperaturaMaxima} onChange={e=>change('temperaturaMaxima',e.target.value)} className="input"/></Field>
    <Field label="Observaciones"><input disabled={!editing} value={form.observaciones} onChange={e=>change('observaciones',e.target.value)} className="input"/></Field>
   </div>{editing&&<div className="flex justify-end gap-2 border-t border-slate-200 p-5"><button onClick={()=>setEditing(false)} className="h-10 border border-slate-300 px-4 text-sm font-semibold">Cancelar</button><button onClick={()=>setConfirm(true)} disabled={!form.cultivoId} className="h-10 bg-amber-700 px-4 text-sm font-semibold text-white disabled:opacity-50">Revisar y guardar</button></div>}
  </div>
  {confirm&&<div className="fixed inset-0 z-[90] flex items-center justify-center bg-slate-950/55 p-4"><div role="dialog" aria-modal="true" className="w-full max-w-lg bg-white shadow-2xl"><div className="flex items-start justify-between border-b p-5"><div><p className="text-xs font-semibold uppercase text-red-700">Acción sensible</p><h2 className="mt-1 text-xl font-bold">Confirmar corrección</h2></div><button title="Cerrar" onClick={()=>setConfirm(false)}><X/></button></div><div className="space-y-4 p-5"><p className="text-sm text-slate-600">El cambio afectará las reglas de riego y dejará el modelo activo en revisión. Los valores anteriores quedarán guardados en el historial y la auditoría.</p><label className="block text-sm font-semibold">Motivo obligatorio<textarea rows="4" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Describe el dato incorrecto y por qué debe corregirse" className="mt-1 w-full resize-none border border-slate-300 p-3 font-normal"/></label><div className="grid grid-cols-2 gap-2"><button onClick={()=>setConfirm(false)} disabled={saving} className="h-11 border border-slate-300 font-semibold">Volver</button><button onClick={submit} disabled={saving||reason.trim().length<10} className="h-11 bg-red-700 font-semibold text-white disabled:opacity-50">{saving?'Guardando...':'Confirmar corrección'}</button></div></div></div></div>}
 </section>
}
function Field({label,children}){return <label className="text-sm font-semibold text-slate-700">{label}{children}</label>}
