import {useCallback,useEffect,useMemo,useState} from 'react'
import {useLocation,useNavigate} from 'react-router-dom'
import {Activity,ChevronRight,CircleHelp,Droplets,Octagon,Plus,Power as Valve,RefreshCcw,ShieldCheck} from 'lucide-react'
import {createActuatorRequest,finishManualTestRequest,getManualTestRequest,listManualCatalogRequest,listManualTestsRequest,startManualTestRequest} from '@/auth/manual-control.service.js'
import {useToast} from '@/context/useToast.js'

const activeStates=['ESPERANDO','EN_CURSO','DETENIENDO']
const format=value=>value?new Date(value).toLocaleString('es-GT',{dateStyle:'short',timeStyle:'medium'}):'—'

export function ManualControlContent(){
 const location=useLocation();const navigate=useNavigate();const toast=useToast();const valves=location.pathname.endsWith('/valvulas');const type=valves?'ACTUADOR':'SENSOR'
 const[nodes,setNodes]=useState([]);const[tests,setTests]=useState([]);const[nodeId,setNodeId]=useState('');const[componentId,setComponentId]=useState('');const[interval,setIntervalValue]=useState(10);const[duration,setDuration]=useState(valves?30:120);const[objective,setObjective]=useState('');const[active,setActive]=useState(null);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[help,setHelp]=useState(null);const[finishOpen,setFinishOpen]=useState(false);const[result,setResult]=useState('APROBADA');const[conclusion,setConclusion]=useState('');const[registerOpen,setRegisterOpen]=useState(false);const[valveForm,setValveForm]=useState({nombre:'Válvula de riego',nodoId:'',pin:5,duracionMaxima:60})
 const load=useCallback(async()=>{setLoading(true);try{const[catalog,history]=await Promise.all([listManualCatalogRequest(),listManualTestsRequest(type)]);setNodes(catalog);setTests(history);const running=history.find(item=>activeStates.includes(item.estado));if(running&&!active)setActive(await getManualTestRequest(running.id))}catch(e){toast.error(e.message)}finally{setLoading(false)}},[active,type,toast])
 useEffect(()=>{setNodeId('');setComponentId('');setActive(null);setDuration(valves?30:120)},[type,valves])
 useEffect(()=>{load()},[load])
 useEffect(()=>{if(!active?.id||!activeStates.includes(active.estado))return;const timer=setInterval(async()=>{try{const next=await getManualTestRequest(active.id);if(activeStates.includes(next.estado))setActive(next);else{setActive(null);await load()}}catch{/* conserva el último estado */}},3000);return()=>clearInterval(timer)},[active?.id,active?.estado,load])
 const node=nodes.find(item=>Number(item.nodo_id)===Number(nodeId));const components=valves?(node?.actuadores||[]):(node?.sensores||[]);const component=components.find(item=>Number(item.id)===Number(componentId));
 const readings=useMemo(()=>active?.lecturas||[],[active?.lecturas]);const stats=useMemo(()=>{const values=readings.map(x=>Number(x.valor)).filter(Number.isFinite);return{count:values.length,min:values.length?Math.min(...values):null,max:values.length?Math.max(...values):null,last:values.at(-1)??null}},[readings])
 const start=async()=>{if(!nodeId||!componentId){toast.warning('Selecciona un nodo y un componente.');return}setSaving(true);try{const data=await startManualTestRequest({tipo:type,nodoId:Number(nodeId),componenteId:Number(componentId),intervaloSegundos:Number(interval),duracionSegundos:Number(duration),objetivo:objective});setActive(await getManualTestRequest(data.pruebaId));toast.success(valves?'Orden enviada con cierre automático.':'Prueba creada; esperando al nodo.');await load()}catch(e){toast.error(e.message)}finally{setSaving(false)}}
 const finish=async(cancel=false)=>{setSaving(true);try{await finishManualTestRequest(active.id,{cancelar:cancel,resultado:result,conclusion});setFinishOpen(false);setActive(null);toast.success(cancel?'Prueba detenida y orden de cierre enviada.':'Resultado guardado y modo normal restaurado.');await load()}catch(e){toast.error(e.message)}finally{setSaving(false)}}
 const createValve=async()=>{setSaving(true);try{await createActuatorRequest({...valveForm,nodoId:Number(valveForm.nodoId),pin:Number(valveForm.pin),duracionMaxima:Number(valveForm.duracionMaxima)});toast.success('Válvula registrada con relé activo en LOW.');setRegisterOpen(false);await load()}catch(e){toast.error(e.message)}finally{setSaving(false)}}
 return <section className="min-h-[calc(100vh-8rem)] rounded-xl border border-slate-200 bg-slate-50 p-4 md:p-6">
  <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.22em] text-green-700">Gestión de control manual</p><h1 className="mt-2 text-3xl font-black">{valves?'Gestión de válvulas':'Pruebas unitarias'}</h1><p className="mt-2 max-w-3xl text-sm text-slate-600">{valves?'Activa actuadores con confirmación, tiempo límite y cierre local de seguridad.':'Obtén lecturas rápidas sin mezclarlas con la telemetría normal ni con la IA.'}</p></div><div className="flex gap-2"><button onClick={load} className="rounded-lg border bg-white p-2.5"><RefreshCcw size={17}/></button>{valves?<button onClick={()=>setRegisterOpen(true)} className="inline-flex items-center gap-2 rounded-lg bg-green-700 px-4 py-2.5 text-sm font-bold text-white"><Plus size={16}/>Registrar válvula</button>:null}</div></div>
  <div className="mt-5 inline-flex rounded-xl border bg-white p-1"><button onClick={()=>navigate('/dashboard/control-manual/pruebas')} className={`rounded-lg px-4 py-2 text-sm font-bold ${!valves?'bg-slate-950 text-white':'text-slate-600'}`}>Pruebas unitarias</button><button onClick={()=>navigate('/dashboard/control-manual/valvulas')} className={`rounded-lg px-4 py-2 text-sm font-bold ${valves?'bg-slate-950 text-white':'text-slate-600'}`}>Gestión de válvulas</button></div>
  {active?<ActiveTest test={active} component={component} stats={stats} valves={valves} onStop={()=>finish(true)} onFinish={()=>setFinishOpen(true)} saving={saving}/>:<div className="mt-6 grid gap-6 xl:grid-cols-[1fr_.85fr]"><div className="rounded-xl border bg-white p-5"><h2 className="font-black">1. Selecciona el nodo</h2><div className="mt-3 grid gap-2 sm:grid-cols-2">{nodes.map(item=><button key={item.nodo_id} onClick={()=>{setNodeId(String(item.nodo_id));setComponentId('')}} className={`rounded-lg border p-3 text-left ${String(item.nodo_id)===nodeId?'border-green-600 bg-green-50':'border-slate-200'}`}><strong>Nodo #{item.nodo_id}</strong><p className="text-xs text-slate-500">{item.tipo_nodo} · {item.estado_energia}</p></button>)}</div><h2 className="mt-6 font-black">2. Selecciona {valves?'la válvula':'el sensor'}</h2><div className="mt-3 space-y-2">{components.map(item=><button key={item.id} onClick={()=>setComponentId(String(item.id))} className={`flex w-full items-center gap-3 rounded-lg border p-3 text-left ${String(item.id)===componentId?'border-green-600 bg-green-50':'border-slate-200'}`}><span className="rounded-lg bg-slate-100 p-2">{valves?<Valve size={18}/>:<Activity size={18}/>}</span><span className="flex-1"><strong className="block">{item.nombre}</strong><small className="text-slate-500">{valves?`${item.estado} · GPIO ${item.pin}`:`${item.tipo} · ${item.unidad||'sin unidad'}`}</small></span>{!valves?<span onClick={event=>{event.stopPropagation();setHelp(item)}} className="rounded-full p-2 hover:bg-white"><CircleHelp size={18}/></span>:null}<ChevronRight size={17}/></button>)}{nodeId&&!components.length?<p className="rounded-lg bg-amber-50 p-4 text-sm text-amber-800">No hay {valves?'válvulas vinculadas':'sensores activos'} en este nodo.</p>:null}</div></div>
   <div className="rounded-xl border bg-white p-5"><h2 className="font-black">3. Configura y confirma</h2><label className="mt-4 block text-sm font-bold">Intervalo de lectura (5–60 s)<input type="number" min="5" max="60" value={interval} onChange={e=>setIntervalValue(e.target.value)} disabled={valves} className="mt-1 w-full rounded-lg border p-2.5 disabled:bg-slate-100"/></label><label className="mt-4 block text-sm font-bold">Duración (30–{valves?(component?.duracionMaxima||60):600} s)<input type="number" min="30" max={valves?(component?.duracionMaxima||60):600} value={duration} onChange={e=>setDuration(e.target.value)} className="mt-1 w-full rounded-lg border p-2.5"/></label><label className="mt-4 block text-sm font-bold">Objetivo<textarea value={objective} onChange={e=>setObjective(e.target.value)} className="mt-1 min-h-24 w-full rounded-lg border p-3" placeholder={valves?'Verificar apertura, flujo y cierre':'Describe el líquido, condición o cambio controlado'}/></label>{valves?<p className="mt-4 rounded-lg border border-amber-200 bg-amber-50 p-3 text-xs text-amber-800"><ShieldCheck className="mr-1 inline" size={15}/>El relé parte inactivo en HIGH y cerrará automáticamente al terminar el tiempo.</p>:null}<button onClick={start} disabled={saving||!component} className="mt-5 w-full rounded-lg bg-green-700 py-3 font-black text-white disabled:opacity-50">{saving?'Enviando…':valves?'Confirmar y abrir temporalmente':'Iniciar prueba rápida'}</button></div></div>}
  <History rows={tests} loading={loading} valves={valves}/>
  {help?<Modal title={`Recomendación · ${help.nombre}`} onClose={()=>setHelp(null)}><div className="flex gap-3 rounded-lg bg-sky-50 p-4 text-sm text-sky-900"><Droplets/><p>{help.recomendacion}</p></div></Modal>:null}
  {finishOpen?<Modal title="Finalizar prueba unitaria" onClose={()=>setFinishOpen(false)}><label className="block text-sm font-bold">Resultado<select value={result} onChange={e=>setResult(e.target.value)} className="mt-1 w-full rounded-lg border p-2.5"><option>APROBADA</option><option>REQUIERE_REVISION</option><option>FALLIDA</option></select></label><label className="mt-4 block text-sm font-bold">Conclusión<textarea value={conclusion} onChange={e=>setConclusion(e.target.value)} className="mt-1 min-h-28 w-full rounded-lg border p-3"/></label><button onClick={()=>finish(false)} disabled={saving} className="mt-5 w-full rounded-lg bg-green-700 py-3 font-bold text-white">Guardar resultado y finalizar</button></Modal>:null}
  {registerOpen?<Modal title="Registrar válvula" onClose={()=>setRegisterOpen(false)}><div className="grid gap-3 sm:grid-cols-2"><Input label="Nombre" value={valveForm.nombre} onChange={v=>setValveForm(x=>({...x,nombre:v}))}/><label className="text-sm font-bold">Nodo<select value={valveForm.nodoId} onChange={e=>setValveForm(x=>({...x,nodoId:e.target.value}))} className="mt-1 w-full rounded-lg border p-2.5"><option value="">Selecciona</option>{nodes.map(n=><option key={n.nodo_id} value={n.nodo_id}>Nodo #{n.nodo_id}</option>)}</select></label><Input label="GPIO" type="number" value={valveForm.pin} onChange={v=>setValveForm(x=>({...x,pin:v}))}/><Input label="Límite seguro (s)" type="number" value={valveForm.duracionMaxima} onChange={v=>setValveForm(x=>({...x,duracionMaxima:v}))}/></div><p className="mt-4 text-xs text-slate-500">Configuración fija: relé activo en LOW e inactivo en HIGH.</p><button onClick={createValve} disabled={saving||!valveForm.nodoId} className="mt-5 w-full rounded-lg bg-green-700 py-3 font-bold text-white">Registrar</button></Modal>:null}
 </section>
}

function ActiveTest({test,stats,valves,onStop,onFinish,saving}){
 if(valves)return <ActuatorExecution test={test} onStop={onStop} onFinish={onFinish} saving={saving}/>
 return <div className="mt-6 rounded-xl border border-green-200 bg-white p-5"><div className="flex flex-wrap justify-between gap-4"><div><p className="text-xs font-black uppercase text-green-700">Prueba #{test.id} · {test.estado}</p><h2 className="mt-1 text-xl font-black">Recepción rápida de lecturas</h2></div><div className="flex gap-2"><button onClick={onStop} disabled={saving} className="inline-flex items-center gap-2 rounded-lg bg-red-700 px-4 py-2 text-sm font-bold text-white"><Octagon size={16}/>Detener</button><button onClick={onFinish} disabled={saving||test.estado==='ESPERANDO'} className="rounded-lg bg-green-700 px-4 py-2 text-sm font-bold text-white">Finalizar prueba</button></div></div><div className="mt-5 grid gap-3 sm:grid-cols-4"><Card label="Muestras" value={stats.count}/><Card label="Mínimo" value={stats.min??'—'}/><Card label="Máximo" value={stats.max??'—'}/><Card label="Última" value={stats.last??'—'}/></div><div className="mt-5 max-h-56 overflow-auto rounded-lg bg-slate-50 p-3">{(test.lecturas||[]).slice().reverse().map(x=><div key={x.id} className="flex justify-between border-b py-2 text-sm"><strong>{x.valor}</strong><span className="text-slate-500">{format(x.fechaHora)}</span></div>)}{!test.lecturas?.length?<p className="py-5 text-center text-sm text-slate-500">Esperando confirmación y datos del nodo…</p>:null}</div></div>
}
function ActuatorExecution({test,onStop,onFinish,saving}){
 const commands=test.comandos||[]
 const activation=commands.find(command=>command.tipo==='ACTIVAR_ACTUADOR')
 const closing=commands.slice().reverse().find(command=>command.tipo==='DESACTIVAR_ACTUADOR')
 const closesAt=test.fechaInicio?new Date(new Date(test.fechaInicio).getTime()+Number(test.duracionSegundos||0)*1000):null
 const remaining=closesAt?Math.max(0,Math.ceil((closesAt.getTime()-Date.now())/1000)):null
 return <div className="mt-6 rounded-xl border border-green-200 bg-white p-5"><div className="flex flex-wrap justify-between gap-4"><div><p className="text-xs font-black uppercase text-green-700">Prueba #{test.id} · {test.estado}</p><h2 className="mt-1 text-xl font-black">Ejecución temporal del actuador</h2><p className="mt-1 text-sm text-slate-500">Sin muestras: esta prueba registra órdenes, tiempos y confirmaciones.</p></div><div className="flex gap-2"><button onClick={onStop} disabled={saving} className="inline-flex items-center gap-2 rounded-lg bg-red-700 px-4 py-2 text-sm font-bold text-white"><Octagon size={16}/>Cerrar ahora</button><button onClick={onFinish} disabled={saving||test.estado==='ESPERANDO'} className="rounded-lg bg-green-700 px-4 py-2 text-sm font-bold text-white">Finalizar y calificar</button></div></div><div className="mt-5 grid gap-3 sm:grid-cols-4"><Card label="Actuador" value={test.componenteNombre||`#${test.actuadorId}`}/><Card label="GPIO" value={test.pinControl??'—'}/><Card label="Duración" value={`${test.duracionSegundos} s`}/><Card label="Cierre automático" value={remaining===null?'Esperando':remaining>0?`${remaining} s`:closing?'Solicitado':'Procesando'}/></div><div className="mt-5 rounded-lg bg-slate-50 p-4"><h3 className="text-sm font-black text-slate-800">Seguimiento de órdenes</h3><CommandRow label="Apertura" command={activation}/><CommandRow label="Cierre" command={closing}/>{!closing&&test.estado==='EN_CURSO'?<p className="mt-3 text-xs text-slate-500">El nodo cerrará localmente al terminar el tiempo y el backend enviará una orden de cierre de respaldo.</p>:null}</div></div>
}
function CommandRow({label,command}){return <div className="mt-3 flex flex-wrap items-center justify-between gap-2 border-t border-slate-200 pt-3 text-sm"><span className="font-bold">{label}</span>{command?<span><strong className={command.estado==='CONFIRMADO'?'text-green-700':'text-amber-700'}>{command.estado}</strong><small className="ml-2 text-slate-500">{format(command.fechaConfirmacion||command.fecha)}</small>{command.mensaje?<small className="block text-right text-slate-500">{command.mensaje}</small>:null}</span>:<span className="text-slate-400">Pendiente</span>}</div>}
function History({rows,loading,valves}){return <div className="mt-6 overflow-hidden rounded-xl border bg-white"><div className="border-b px-5 py-4"><h2 className="font-black">Historial formal de pruebas</h2></div>{loading?<p className="p-6 text-center text-sm text-slate-500">Consultando…</p>:rows.length?rows.map(row=><div key={row.id} className="grid gap-2 border-b px-5 py-3 text-sm sm:grid-cols-[70px_1fr_130px_170px]"><strong>#{row.id}</strong><span>{row.componente} · {row.usuario}<small className="block text-slate-500">{valves?`${row.duracion_segundos} s programados`:`${row.total_lecturas} muestras`} · {format(row.fecha_hora)}</small>{row.conclusion?<small className="mt-1 block text-slate-500">{row.conclusion}</small>:null}</span><span>{row.estado}</span><strong className="text-green-800">{(row.resultado||'Pendiente').replaceAll('_',' ')}</strong></div>):<p className="p-6 text-center text-sm text-slate-500">Aún no hay pruebas registradas.</p>}</div>}
function Card({label,value}){return <div className="rounded-lg bg-slate-50 p-3"><p className="text-xs font-bold text-slate-500">{label}</p><p className="mt-1 text-xl font-black">{value}</p></div>}
function Input({label,value,onChange,type='text'}){return <label className="text-sm font-bold">{label}<input type={type} value={value} onChange={e=>onChange(e.target.value)} className="mt-1 w-full rounded-lg border p-2.5"/></label>}
function Modal({title,onClose,children}){return <div className="fixed inset-0 z-[90] flex items-center justify-center bg-black/50 p-4"><div className="w-full max-w-lg rounded-xl bg-white p-5"><div className="flex justify-between"><h3 className="text-xl font-black">{title}</h3><button onClick={onClose}>Cerrar</button></div><div className="mt-5">{children}</div></div></div>}
