import { useEffect,useMemo,useState } from 'react'
import { Download,FileSpreadsheet,FileText,Printer } from 'lucide-react'
import { listFieldReportsRequest } from '@/auth/reports.service.js'
import { listTelemetryHardwareRequest } from '@/auth/hardware.service.js'
import { useToast } from '@/context/useToast.js'

const today=new Date().toISOString().slice(0,10)
const monthAgo=new Date(Date.now()-30*86400000).toISOString().slice(0,10)
const escapeCsv=value=>`"${String(value??'').replaceAll('"','""')}"`
const download=(content,type,name)=>{const url=URL.createObjectURL(new Blob([content],{type}));const link=document.createElement('a');link.href=url;link.download=name;link.click();URL.revokeObjectURL(url)}

function chartsHtml(rows){
 const ordered=[...rows].reverse();const values=ordered.map(row=>Number(row.valorLectura)).filter(Number.isFinite)
 if(!values.length)return'<div class="empty">No hay lecturas para generar gráficas.</div>'
 const min=Math.min(...values),max=Math.max(...values);const span=max-min||1
 const points=values.map((value,index)=>`${values.length===1?50:(index/(values.length-1))*100},${90-((value-min)/span)*75}`).join(' ')
 const grouped=new Map();rows.forEach(row=>{const key=row.tipoComponente||'Sin componente';const list=grouped.get(key)||[];const value=Number(row.valorLectura);if(Number.isFinite(value))list.push(value);grouped.set(key,list)})
 const averages=[...grouped].map(([name,list])=>({name,value:list.reduce((a,b)=>a+b,0)/list.length}));const averageMax=Math.max(...averages.map(item=>item.value),1)
 return `<div class="charts"><section class="chart"><h3>Evolución de lecturas recientes</h3><svg viewBox="0 0 100 100" preserveAspectRatio="none"><line x1="0" y1="92" x2="100" y2="92" stroke="#dbe4df"/><polyline points="${points}" fill="none" stroke="#15803d" stroke-width="3" stroke-linecap="round" stroke-linejoin="round" vector-effect="non-scaling-stroke"/></svg><div class="legend"><span>Mínimo: ${min.toFixed(2)}</span><span>Máximo: ${max.toFixed(2)}</span></div></section><section class="chart"><h3>Promedio por componente</h3>${averages.map(item=>`<div class="bar-row"><div><span>${item.name}</span><strong>${item.value.toFixed(2)}</strong></div><div class="track"><div class="fill" style="width:${Math.max((item.value/averageMax)*100,2)}%"></div></div></div>`).join('')}</section></div>`
}

export function ReportExportContent(){
 const toast=useToast();const[from,setFrom]=useState(monthAgo);const[to,setTo]=useState(today);const[reports,setReports]=useState([]);const[telemetry,setTelemetry]=useState([]);const[sections,setSections]=useState({resumen:true,telemetria:true,informes:true,graficas:true})
 useEffect(()=>{Promise.all([listFieldReportsRequest(),listTelemetryHardwareRequest({limit:10})]).then(([items,data])=>{setReports(items);setTelemetry(data.telemetrias.slice(0,10))}).catch(error=>toast.error(error.message))},[toast])
 const data=useMemo(()=>{const inRange=value=>{const day=String(value||'').slice(0,10);return(!from||day>=from)&&(!to||day<=to)};return{reports:reports.filter(item=>inRange(item.fecha_observacion)),telemetry:telemetry.filter(item=>inRange(item.fechaHora)).slice(0,10)}},[from,to,reports,telemetry])
 const summary=useMemo(()=>{const values=data.telemetry.map(item=>Number(item.valorLectura)).filter(Number.isFinite);return{lecturas:values.length,promedio:values.length?(values.reduce((a,b)=>a+b,0)/values.length).toFixed(2):'Sin datos',informes:data.reports.length}},[data])
 const html=()=>`<!doctype html><html><head><meta charset="utf-8"><title>Reporte del proyecto</title><style>@page{size:A4;margin:16mm}*{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#172033;margin:0}h1{color:#166534;margin-bottom:4px}h2{margin-top:28px;border-bottom:2px solid #dcfce7;padding-bottom:7px}.period{color:#64748b}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:20px 0}.card{border:1px solid #dbe4df;border-radius:10px;padding:14px}.card strong{display:block;font-size:24px;color:#166534;margin-top:5px}.charts{display:grid;grid-template-columns:1fr 1fr;gap:16px}.chart{border:1px solid #dbe4df;border-radius:10px;padding:14px;break-inside:avoid}.chart svg{width:100%;height:180px;background:#f8fafc}.legend,.bar-row>div:first-child{display:flex;justify-content:space-between;font-size:11px;margin-top:7px}.track{height:12px;background:#e2e8f0;border-radius:10px;overflow:hidden}.fill{height:100%;background:#15803d}.bar-row{margin:13px 0}.empty{padding:25px;background:#f8fafc;color:#64748b}table{width:100%;border-collapse:collapse;margin-top:12px;font-size:11px}th{background:#166534;color:white}th,td{border:1px solid #dbe4df;padding:7px;text-align:left}tr{break-inside:avoid}@media print{button{display:none}}</style></head><body><h1>Reporte del proyecto</h1><p class="period">Período: ${from} al ${to}</p>${sections.resumen?`<div class="cards"><div class="card">Lecturas recientes<strong>${summary.lecturas}</strong></div><div class="card">Promedio general<strong>${summary.promedio}</strong></div><div class="card">Informes de campo<strong>${summary.informes}</strong></div></div>`:''}${sections.graficas?`<h2>Gráficas de telemetría</h2>${chartsHtml(data.telemetry)}`:''}${sections.telemetria?`<h2>Últimas lecturas de telemetría</h2><table><tr><th>Fecha</th><th>Nodo</th><th>Componente</th><th>Valor</th></tr>${data.telemetry.map(x=>`<tr><td>${new Date(x.fechaHora).toLocaleString('es-GT')}</td><td>${x.tbNodoId||''}</td><td>${x.tipoComponente}</td><td>${x.valorLectura??''}</td></tr>`).join('')}</table>`:''}${sections.informes?`<h2>Informes</h2><table><tr><th>Número</th><th>Fecha</th><th>Título</th><th>Estado</th></tr>${data.reports.map(x=>`<tr><td>#${String(x.id).padStart(4,'0')}</td><td>${x.fecha_observacion||''}</td><td>${x.titulo}</td><td>${x.estado_general||''}</td></tr>`).join('')}</table>`:''}</body></html>`
 const excel=()=>{const lines=[];if(sections.telemetria)lines.push('ÚLTIMAS 10 LECTURAS','Fecha,Nodo,Componente,Valor',...data.telemetry.map(x=>[x.fechaHora,x.tbNodoId,x.tipoComponente,x.valorLectura].map(escapeCsv).join(',')),'');if(sections.informes)lines.push('INFORMES','Número,Fecha,Título,Estado',...data.reports.map(x=>[x.id,x.fecha_observacion,x.titulo,x.estado_general].map(escapeCsv).join(',')));download('\ufeff'+lines.join('\n'),'text/csv;charset=utf-8','reporte-proyecto-excel.csv')}
 const word=()=>download(html(),'application/msword','reporte-proyecto.doc')
 const pdf=()=>{const win=window.open('','_blank');if(!win)return toast.warning('Permite ventanas emergentes para imprimir el reporte.');win.document.write(html());win.document.close();setTimeout(()=>win.print(),300)}
 const toggle=key=>setSections(current=>({...current,[key]:!current[key]}))
 const labels={resumen:'Resumen general',telemetria:'Últimas 10 lecturas de telemetría',informes:'Informes de campo',graficas:'Gráficas de telemetría'}
 return <div className="space-y-5"><div className="rounded-xl border bg-white p-5"><h2 className="font-black">Configurar reporte</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Desde<input type="date" value={from} max={to} onChange={e=>setFrom(e.target.value)} className="mt-1 block w-full rounded-lg border p-2.5"/></label><label className="text-sm font-bold">Hasta<input type="date" value={to} min={from} onChange={e=>setTo(e.target.value)} className="mt-1 block w-full rounded-lg border p-2.5"/></label></div><p className="mt-5 text-sm font-black">Contenido del reporte</p><div className="mt-2 grid gap-2 sm:grid-cols-2">{Object.entries(labels).map(([key,label])=><label key={key} className="flex items-center gap-3 rounded-lg bg-slate-50 p-3 text-sm font-semibold"><input type="checkbox" checked={sections[key]} onChange={()=>toggle(key)} className="accent-green-700"/>{label}</label>)}</div><p className="mt-3 text-xs text-slate-500">Para mantener el reporte breve, la telemetría se limita a las 10 lecturas más recientes del período. Puedes excluirla desmarcando su opción.</p></div><div className="grid gap-3 sm:grid-cols-3"><button onClick={excel} className="flex items-center justify-center gap-2 rounded-xl bg-green-700 p-4 font-bold text-white"><FileSpreadsheet/>Exportar Excel</button><button onClick={word} className="flex items-center justify-center gap-2 rounded-xl bg-blue-700 p-4 font-bold text-white"><FileText/>Exportar Word</button><button onClick={pdf} className="flex items-center justify-center gap-2 rounded-xl bg-slate-800 p-4 font-bold text-white"><Printer/>Imprimir / PDF</button></div><div className="rounded-xl border bg-white p-5"><div className="flex items-center gap-2"><Download className="text-green-700"/><h2 className="font-black">Vista previa</h2></div><p className="mt-3 text-sm text-slate-600">{summary.lecturas} lecturas recientes y {summary.informes} informes encontrados entre {from} y {to}.</p></div></div>
}
