import {useCallback,useEffect,useMemo,useState} from 'react'
import {Activity,CheckCircle2,Droplets,Power,RefreshCcw,Sun} from 'lucide-react'
import {useNavigate} from 'react-router-dom'
import {calibrateSensorRequest,finishManualTestRequest,getManualTestRequest,listManualCatalogRequest,listManualTestsRequest,startManualTestRequest} from '@/auth/manual-control.service.js'
import {switchNodeEnergyRequest} from '@/auth/hardware.service.js'
import {useToast} from '@/context/useToast.js'

const runningStates=['ESPERANDO','EN_CURSO','DETENIENDO']
const average=values=>values.reduce((sum,value)=>sum+value,0)/values.length

export function SensorCalibrationContent(){
 const navigate=useNavigate();const toast=useToast();const[nodes,setNodes]=useState([]);const[nodeId,setNodeId]=useState('');const[sensorId,setSensorId]=useState('');const[test,setTest]=useState(null);const[dry,setDry]=useState(null);const[wet,setWet]=useState(null);const[dryCount,setDryCount]=useState(0);const[saving,setSaving]=useState(false);const[loading,setLoading]=useState(true)
 const load=useCallback(async()=>{setLoading(true);try{const[catalog,tests]=await Promise.all([listManualCatalogRequest(),listManualTestsRequest('SENSOR')]);setNodes(catalog);const active=tests.find(item=>runningStates.includes(item.estado));if(active){const detail=await getManualTestRequest(active.id);if(/higr|hum/i.test(detail?.componenteNombre||'')){setTest(detail);setNodeId(String(detail.nodoId));setSensorId(String(detail.sensorId))}}}catch(error){toast.error(error.message)}finally{setLoading(false)}},[toast])
 useEffect(()=>{load()},[load])
 useEffect(()=>{if(!test?.id||!runningStates.includes(test.estado))return;const timer=window.setInterval(()=>getManualTestRequest(test.id).then(setTest).catch(()=>{}),2000);return()=>window.clearInterval(timer)},[test?.id,test?.estado])
 const node=nodes.find(item=>Number(item.nodo_id)===Number(nodeId));const sensors=(node?.sensores||[]).filter(item=>/higr|hum/i.test(item.tipo));const sensor=sensors.find(item=>Number(item.id)===Number(sensorId));const readings=useMemo(()=>(test?.lecturas||[]).map(item=>Number(item.valor)).filter(Number.isFinite),[test?.lecturas])
 const toggle=async(state)=>{setSaving(true);try{await switchNodeEnergyRequest(Number(nodeId),state);toast.success(state==='APAGADO'?'Nodo apagado para intervención técnica.':'Nodo habilitado para telemetría normal.');await load()}catch(error){toast.error(error.message)}finally{setSaving(false)}}
 const start=async()=>{if(!sensor||node?.estado_energia!=='APAGADO')return;setSaving(true);try{const data=await startManualTestRequest({tipo:'SENSOR',nodoId:Number(nodeId),componenteId:Number(sensorId),intervaloSegundos:5,duracionSegundos:600,objetivo:'Calibración controlada del punto seco y húmedo'});setTest(await getManualTestRequest(data.pruebaId));setDry(null);setWet(null);setDryCount(0);toast.success('Prueba iniciada. Espera lecturas estables en tierra seca.')}catch(error){toast.error(error.message)}finally{setSaving(false)}}
 const captureDry=()=>{const sample=readings.slice(-5);if(sample.length<3){toast.warning('Espera al menos 3 lecturas antes de capturar.');return}setDry(Number(average(sample).toFixed(2)));setWet(null);setDryCount(readings.length);toast.success('Punto seco capturado. Ahora coloca el sensor en tierra mojada.')}
 const captureWet=()=>{const sample=readings.slice(dryCount).slice(-5);if(sample.length<3){toast.warning('Espera al menos 3 lecturas nuevas en tierra mojada.');return}setWet(Number(average(sample).toFixed(2)));toast.success('Punto húmedo capturado. Revisa y confirma la calibración.')}
 const cancel=async()=>{if(!test?.id)return;setSaving(true);try{await finishManualTestRequest(test.id,{cancelar:true,conclusion:'Calibración cancelada para reiniciar el procedimiento'});toast.success('Calibración cancelada. Ya puedes iniciar una nueva.');setTest(null);setDry(null);setWet(null);setDryCount(0);await load()}catch(error){toast.error(error.message)}finally{setSaving(false)}}
 const save=async()=>{if(dry===null||wet===null)return;setSaving(true);try{await calibrateSensorRequest(sensor.id,{pruebaId:test.id,adcSeco:dry,adcHumedo:wet});await finishManualTestRequest(test.id,{resultado:'APROBADA',conclusion:`Calibración ADC: seco ${dry}, húmedo ${wet}`});toast.success('Calibración guardada. Ya puedes encender el nodo.');setTest(null);setDry(null);setWet(null);await load()}catch(error){toast.error(error.message)}finally{setSaving(false)}}
 return <section className="min-h-[calc(100vh-8rem)] bg-slate-50 p-4 md:p-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase text-green-700">Gestión de control manual</p><h1 className="mt-2 text-3xl font-black">Calibración de sensores</h1><p className="mt-2 max-w-3xl text-sm text-slate-600">Define los extremos ADC del higrómetro antes de habilitar la telemetría y el riego automático.</p></div><button onClick={load} className="border bg-white p-2.5" title="Actualizar"><RefreshCcw size={17}/></button></div>
 <div className="mt-5 inline-flex border bg-white p-1"><button onClick={()=>navigate('/dashboard/control-manual/pruebas')} className="px-4 py-2 text-sm font-bold text-slate-600">Pruebas unitarias</button><button className="bg-slate-950 px-4 py-2 text-sm font-bold text-white">Calibración</button><button onClick={()=>navigate('/dashboard/control-manual/valvulas')} className="px-4 py-2 text-sm font-bold text-slate-600">Válvulas</button></div>
 {loading?<p className="mt-6 bg-white p-8 text-center text-slate-500">Consultando sensores...</p>:<div className="mt-6 grid gap-6 xl:grid-cols-[.8fr_1.2fr]"><div className="border bg-white p-5"><h2 className="font-black">Nodo y sensor</h2><select value={nodeId} disabled={Boolean(test)} onChange={event=>{setNodeId(event.target.value);setSensorId('')}} className="mt-4 w-full border p-2.5"><option value="">Selecciona un nodo</option>{nodes.map(item=><option key={item.nodo_id} value={item.nodo_id}>Nodo #{item.nodo_id} · {item.estado_energia}</option>)}</select><div className="mt-3 space-y-2">{sensors.map(item=><button key={item.id} disabled={Boolean(test)} onClick={()=>setSensorId(String(item.id))} className={`flex w-full items-center gap-3 border p-3 text-left ${String(item.id)===sensorId?'border-green-600 bg-green-50':'border-slate-200'}`}><Activity size={18}/><span className="flex-1"><strong className="block">{item.nombre}</strong><small className="text-slate-500">{item.calibrado?`Calibrado · seco ${item.adcSeco}, húmedo ${item.adcHumedo}`:'Pendiente de calibración'}</small></span>{item.calibrado?<CheckCircle2 className="text-green-700" size={18}/>:null}</button>)}</div>{nodeId&&!sensors.length?<p className="mt-3 bg-amber-50 p-3 text-sm text-amber-800">Este nodo no tiene higrómetros activos.</p>:null}{node?<button disabled={saving} onClick={()=>toggle(node.estado_energia==='APAGADO'?'ENCENDIDO':'APAGADO')} className={`mt-4 flex w-full items-center justify-center gap-2 p-3 font-bold text-white ${node.estado_energia==='APAGADO'?'bg-green-700':'bg-slate-800'}`}><Power size={17}/>{node.estado_energia==='APAGADO'?'Encender nodo':'Apagar para calibrar'}</button>:null}</div>
 <div className="border bg-white p-5"><div className="flex items-center justify-between gap-3"><h2 className="font-black">Procedimiento guiado</h2>{test?<button onClick={cancel} disabled={saving} className="border border-red-300 px-3 py-2 text-sm font-bold text-red-700 disabled:opacity-40">Cancelar y reiniciar</button>:null}</div>{!test?<><Step number="1" title="Apaga el nodo" text="La telemetría normal queda suspendida mientras se realiza la intervención." done={node?.estado_energia==='APAGADO'}/><Step number="2" title="Selecciona el higrómetro" text="La prueba rápida obtendrá muestras sin guardarlas como telemetría normal." done={Boolean(sensor)}/><button onClick={start} disabled={saving||!sensor||node?.estado_energia!=='APAGADO'} className="mt-5 w-full bg-green-700 py-3 font-black text-white disabled:opacity-40">Iniciar calibración</button></>:<><Step number="1" icon={Sun} title="Coloca el sensor en tierra seca" text="Espera varias lecturas estables y captura el promedio." done={dry!==null}/><Reading value={readings.at(-1)} count={readings.length}/><button onClick={captureDry} disabled={dry!==null} className="mt-3 w-full border border-amber-600 py-2.5 font-bold text-amber-800 disabled:opacity-40">Capturar punto seco</button><Step number="2" icon={Droplets} title="Coloca el sensor en tierra completamente mojada" text="Después del cambio espera al menos tres lecturas nuevas." done={wet!==null}/><button onClick={captureWet} disabled={dry===null||wet!==null} className="mt-3 w-full border border-sky-600 py-2.5 font-bold text-sky-800 disabled:opacity-40">Capturar punto húmedo</button>{dry!==null&&wet!==null?<div className={`mt-5 border p-4 ${dry-wet>=50?'border-green-300 bg-green-50':'border-red-300 bg-red-50'}`}><p className="font-bold">Seco: {dry} ADC · Húmedo: {wet} ADC</p><p className="mt-1 text-sm">Separación: {(dry-wet).toFixed(2)} ADC {dry-wet>=50?'· válida':'· insuficiente'}</p><button onClick={save} disabled={saving||dry-wet<50} className="mt-4 w-full bg-green-700 py-3 font-black text-white disabled:opacity-40">Guardar calibración</button></div>:null}</>}</div></div>}</section>
}

function Step({number,icon:Icon,title,text,done}){return <div className={`mt-4 flex gap-3 border p-4 ${done?'border-green-200 bg-green-50':'border-slate-200'}`}><span className="flex h-8 w-8 shrink-0 items-center justify-center bg-slate-900 font-black text-white">{Icon?<Icon size={17}/>:number}</span><div><p className="font-black">{title}</p><p className="text-sm text-slate-600">{text}</p></div></div>}
function Reading({value,count}){return <div className="mt-3 grid grid-cols-2 gap-3"><div className="bg-slate-100 p-3"><p className="text-xs font-bold text-slate-500">Última lectura</p><p className="text-2xl font-black">{value??'—'} ADC</p></div><div className="bg-slate-100 p-3"><p className="text-xs font-bold text-slate-500">Muestras</p><p className="text-2xl font-black">{count}</p></div></div>}
