import { Router } from "express";
import { configure, evaluate, resolve, restore, retraining, state, train } from "../controllers/ai.controller.js";
import { verifyToken } from "../middlewares/jwt.middleware.js";
import { requireProjectAdministrator, verifyProjectAccess } from "../middlewares/project.middleware.js";
const router=Router();
router.use(verifyToken,verifyProjectAccess);
router.get("/estado",state);
router.get("/reentrenamiento",retraining);
router.post("/entrenar",requireProjectAdministrator,train);
router.post("/evaluar",requireProjectAdministrator,evaluate);
router.patch("/decisiones/:id/resolver",requireProjectAdministrator,resolve);
router.put("/configuracion",requireProjectAdministrator,configure);
router.post("/versiones/:id/restaurar",requireProjectAdministrator,restore);
export default router;
